{% set name = "anaconda-catalogs" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anaconda-catalogs-{{ version }}.tar.gz
  sha256: 9f9396ced850ec377fd6ef0d9be43bb6f62dd0a61da69582d077458e3bb12e7d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp
    - intake
    - requests

test:
  imports:
    - anaconda_catalogs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/anaconda/anaconda-catalogs
  summary: Client library for Anaconda Catalogs
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mattkram
    - millsks
    - rxm7706
